import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Promobar from "./components/promoBar/promobar";
import CartProvider from "./components/Providers/providers";
import ShoppingCartModal from "./components/ShoppingCartModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="ApercuPro">
        <CartProvider>
          <Promobar />
          <Navbar />
          <ShoppingCartModal />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
